# Generated by Django 4.1.2 on 2022-11-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IKSAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='', max_length=50)),
                ('Range', models.CharField(default='', max_length=50)),
                ('Lat', models.FloatField(null=True)),
                ('Lon', models.FloatField(null=True)),
            ],
        ),
    ]
